[package]
name = "forge-program"
description = "COAL is a fair-launch, proof-of-work, digital currency everyone can mine"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "forge"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))', 'cfg(feature, values("custom-heap", "custom-panic"))'] }

[dependencies]
forge-api.workspace = true
mpl-core.workspace = true
solana-program.workspace = true
steel.workspace = true