[package]
name = "forge-program"
description = "COAL is a fair-launch, proof-of-work, digital currency everyone can mine"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "forge"

[features]
no-entrypoint = []
default = []

[dependencies]
drillx.workspace = true
mpl-token-metadata.workspace = true
forge-api.workspace = true
forge-utils.workspace = true
solana-program.workspace = true
spl-token.workspace = true
spl-associated-token-account.workspace = true
mpl-core.workspace = true
borsh.workspace = true